### ISSUE TITLE
Markers (+ Notes) are not displayed

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#35]
When selecting "Markers" it will show "-" for a clip that has a Marker+Notes applied. But it will display the option Marker+Notes correctly.
When selecting "Markers+Notes" and a clip only has a Marker applied it will also show "-".

[_Metaburner Test.zip](https://github.com/latenitefilms/Metaburner/files/13919943/_Metaburner.Test.zip)

**Comment by samplue** [comment]
[_Metaburner Test New.zip](https://github.com/latenitefilms/Metaburner/files/13920109/_Metaburner.Test.New.zip)

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.
