### ISSUE TITLE
Keyframed values (Scale, Position, Rotation, Opacity) are displayed with their start values and do not update

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#36]
I've applied keyframed values to a clip. "Scale" doesn't show values for each frame, but remains at "x = 100.00, y = 100.00" through the entire shot. Same applies for "Rotation", "Position", "Opacity".

[_Metaburner Test.zip](https://github.com/latenitefilms/Metaburner/files/13919958/_Metaburner.Test.zip)

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.
