### ISSUE TITLE
Marker won't show up for certain configurations

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#38]
"Marker + Notes" display correctly now, but some configurations still return "-" on-screen instead of the markers content.

- Text layer is set to display "Marker" only - but marker has also a note displayed - the Marker content won't show up. Another Text layer will, however, display the "Notes" content. -> Please check the first clip on the timeline and Text Layer 1 + Text Layer 4 of the Metaburner Title.
[Metaburner Marker Bug.zip](https://github.com/latenitefilms/Metaburner/files/13939383/Metaburner.Marker.Bug.zip)

**Comment by latenitefilms** [comment]
This is a regression. I broke something when I was trying to clean up the code. This will be fixed in the next beta.
