### ISSUE TITLE
Metaburner is stuck in "Analyzing Project..."

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#41]
Metaburner is either stuck in "Analyzing Project..." or becomes unresponsive so that the Inspector UI won't update. This happens on a very short timeline with just 5 audio clips, but also on a fairly large 30 min timeline.

![Sam_2024-01-17_17h08m57](https://github.com/latenitefilms/Metaburner/assets/78317416/049bf212-b887-4178-9597-d84b1d1373d1)

[Metaburner Renderer - 1.0.2 (30).log](https://github.com/latenitefilms/Metaburner/files/13965576/Metaburner.Renderer.-.1.0.2.30.log)
[Metaburner Renderer-2024-01-17-165032.ips.zip](https://github.com/latenitefilms/Metaburner/files/13965585/Metaburner.Renderer-2024-01-17-165032.ips.zip)

[Audio-Timeline.zip](https://github.com/latenitefilms/Metaburner/files/13965597/Audio-Timeline.zip)
[Complex-Timeline.fcpxmld.zip](https://github.com/latenitefilms/Metaburner/files/13965598/Complex-Timeline.fcpxmld.zip)

**Comment by latenitefilms** [comment]
Ummm... unfortunately I don't think there's much helpful information in the crash log or log files as to why it's crashing/failing in that case.

Interestingly, `Complex-Timeline.fcpxmld` has a DTD validation error - so I can't import that into FCPX:

<img width="260" alt="image" src="https://github.com/latenitefilms/Metaburner/assets/22286696/e8ae699e-41c6-4ef5-aef7-bcbdeda24a8a">

If you exported this from FCPX without any modification, then it's a FCPX bug, and you should report to Apple.

However, your `_Metaburner Audio Role Bug` example has brought up some interesting things:

<img width="1179" alt="image" src="https://github.com/latenitefilms/Metaburner/assets/22286696/177d26c7-3d42-4bd6-8e53-cf2b2be93a73">

All these clips are in lane -1, so I'm not really sure how to deal with that.

**Comment by latenitefilms** [comment]
The crash was a regression introduced when we added support for anchored clips. 

Will hopefully be fixed in next beta.

**Comment by samplue** [comment]
Thanks, I've shared the faulty fcpxml with the ProApps team to see what's causing the issue.
