### ISSUE TITLE
Support for Compound clips

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#43]
It would be a gread addition if Metaburner was able to analyze compound clips as well. During the editing process we work in reels, so we have Reel 1, 2 and 3 - each around 30 mins - in compound clips and I'd like to skip the process of "Break Apart Item" each time I need to add the metaburner title.

**Comment by latenitefilms** [comment]
How would that work exactly?

Do you just want "Primary Storyline - Inside Container - 1st Video Clip" to be able to "look inside" Compound Clips, like it can Sync Clip's currently?

**Comment by samplue** [comment]
In our case I would like to open the compound clip in its own timeline, place the marker on top of all clips and then drag-drop the compound clip on the metaburner tool.

![Uploading Sam_2024-01-18_10h46m55.png…]()

**Comment by latenitefilms** [comment]
Oh, I see what you mean now.

**Comment by latenitefilms** [comment]
This will be added in the next beta.

**Comment by samplue** [comment]
Just tested this with inside two of our compound clips and got the following error message:

![Sam_2024-01-25_12h21m47](https://github.com/latenitefilms/Metaburner/assets/78317416/8f772666-8603-4d56-b8f9-2abca071a428)
[Metaburner Renderer - 1.0.7 (35).log](https://github.com/latenitefilms/Metaburner/files/14050912/Metaburner.Renderer.-.1.0.7.35.log)
