### ISSUE TITLE
Changing "Alignment" doesn't actually change anything

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#44]
Changing the Alignment setting in the Global settings as well as in the individual layers doesn't have the desired effect. The text does not change whether it is set to "Left", "Center" or "Right".
![Sam_2024-01-19_16h34m13](https://github.com/latenitefilms/Metaburner/assets/78317416/a58b0511-50dd-4c3b-a13f-0022dc2d451a)

**Comment by latenitefilms** [comment]
Huh, that's weird. It definitely was working at some point. I must have broken something.

**Comment by latenitefilms** [comment]
Actually, you can see it working if there's multiple lines:

<img width="1113" alt="image" src="https://github.com/latenitefilms/Metaburner/assets/22286696/f81d2eaa-bed0-4d9b-94d3-f23ba95e8273">

**Comment by samplue** [comment]
Will give this a try tomorrow, but are you saying that it doesn't work with 1 line, but 2 lines it does?

**Comment by latenitefilms** [comment]
Yeah, it looks like currently the alignment basically only does anything when you have more than one line of text. It no longer changes the "anchor point" of the text. I think this might of changed when I built the on-screen controls. Will have to have a think about how I can get both working.

**Comment by latenitefilms** [comment]
This will finally be fixed in **Metaburner v1.1.0-beta.11**.
