### ISSUE TITLE
Option to disable the Marker "type"

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#45]
I would love to see an option to toggle the Marker type on or off. I use markers for labeling VFX shots and in that case it's rather confusing to display the marker type (Chapter, To Do, etc...).

![Sam_2024-01-19_16h48m58](https://github.com/latenitefilms/Metaburner/assets/78317416/55bbaa01-1d10-4669-8776-cd4478621c83)

**Comment by latenitefilms** [comment]
This will be added as new Content Fields in the next beta:

<img width="1094" alt="image" src="https://github.com/latenitefilms/Metaburner/assets/22286696/27e5a692-a506-48ee-8f34-7b347c514b4b">
