### ISSUE TITLE
Option to disable "-" for empty content

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#46]
Currently when there is no data available for a text layer it will display "-". I'd love to see an option to turn it off/display nothin at all when there is no data available. 

Example: I tag all VFX shots with a marker. 5 out of 100 shots have a marker, but I want Text Layer 01 to display the Marker Name, it is rather disctracting to see "-" on the other 95 shots. I want to place the Metaburner title over the entire timeline as it should display Project timecode on another layer.

![Sam_2024-01-19_17h04m10](https://github.com/latenitefilms/Metaburner/assets/78317416/f1604472-e8da-419e-8cd2-737ede29aa0e)

**Comment by latenitefilms** [comment]
An **Empty Data** text field will be added to the **Global Settings** in the next beta.
