### ISSUE TITLE
Copy/Paste the Metaburner title does not work

### ISSUE THREAD

**Issue by samplue** [latenitefilms/Metaburner#52]
I should probably use presets, but I havent been able to copy/paste a Metaburner title from one timeline to another or within the same timeline. Sometimes it would be just quicker and easier to copy/paste the title to another section of the timeline. This also doesn't work when I've cleared the "Project Data" before.

**Comment by latenitefilms** [comment]
That is SUPER WEIRD. I have no idea why Final Cut Pro doesn't allow you to paste this Title.

It also doesn't look like you can OPTION+DRAG it.

It SHOULD just be a standard Motion Title, so I have no idea what's going wrong.

**Comment by latenitefilms** [comment]
It has something to do with the Motion Template, but I'm not sure what yet.

Creating a new Motion Template with no published parameters works fine.

**Comment by latenitefilms** [comment]
This will be fixed in the next beta.

Apparently FCPX really didn't like me saving MB's of data as a FxPlug Parameter.
